# Maintainer: Ivan <ivan@primaguna.com>
pkgname=antibising
pkgver=0.1.0
pkgrel=1
pkgdesc='Permanent noise-suppressed virtual microphone for Linux (PipeWire + RNNoise)'
arch=('x86_64')
url='https://github.com/ivanp/antibising'
license=('MIT')
depends=('pipewire' 'systemd' 'webkit2gtk-4.1' 'gtk3'
         'noise-suppression-for-voice' 'hicolor-icon-theme')
makedepends=('rust')
source=()   # builds from the checkout containing this PKGBUILD
sha256sums=()

build() {
    cd "$startdir"
    cargo build --release --locked
}

package() {
    cd "$startdir"

    # daemon binary (ExecStart=/usr/bin/antibisingd run)
    install -Dm755 target/release/antibisingd "$pkgdir/usr/bin/antibisingd"

    # GUI app — cargo package name is "app"; installed under the product name
    install -Dm755 target/release/app "$pkgdir/usr/bin/antibising"

    # Systemd user unit.
    # Content mirrors engine/src/install.rs::render_daemon_unit() exactly,
    # with ExecStart hardcoded to the installed path instead of current_exe().
    install -Dm644 /dev/stdin \
        "$pkgdir/usr/lib/systemd/user/antibisingd.service" <<'EOF'
# Generated by antibising package
[Unit]
Description=antibising permanent-microphone daemon
Wants=pipewire.service
After=pipewire.service

[Service]
Type=simple
ExecStart=/usr/bin/antibisingd run
Restart=on-failure

[Install]
WantedBy=default.target
EOF

    # PipeWire crash-recovery drop-in (R2).
    # Mirrors engine/src/install.rs::render_pipewire_dropin().
    # Upholds= re-pulls filter-chain.service after a PipeWire crash;
    # without it the permanent source stays dead until the next daemon restart.
    install -Dm644 /dev/stdin \
        "$pkgdir/usr/lib/systemd/user/pipewire.service.d/10-antibising.conf" <<'EOF'
# Generated by antibising package
[Unit]
Upholds=filter-chain.service
EOF

    # Application icon (32×32 RGBA PNG — the only size shipped by the repo).
    install -Dm644 app/icons/icon.png \
        "$pkgdir/usr/share/icons/hicolor/32x32/apps/antibising.png"

    # Desktop entry.  Exec= matches the installed binary name above.
    install -Dm644 /dev/stdin \
        "$pkgdir/usr/share/applications/antibising.desktop" <<'EOF'
[Desktop Entry]
Type=Application
Name=antibising
Comment=Permanent noise-suppressed virtual microphone
Exec=antibising
Icon=antibising
Terminal=false
Categories=Audio;AudioVideo;
EOF
}

post_install() {
    echo "==> Enable and start the daemon:  systemctl --user enable --now antibisingd.service"
    echo "==> Launch the GUI:  antibising  (or via the app menu)"
}
