//! Generates the `filter-chain` conf.d fragment that defines the permanent
//! source (U2), later extended with the RNNoise node (U5).
//!
//! ## The downmix hazard and its fix
//!
//! A stereo device links to a `[ MONO ]` capture port whether or not the
//! filter graph asked for it, and the adapter's default mix is a **sum at
//! unity gain per channel** — measured this session at 63.2% samples
//! clipped for a 0.92 FS stereo input. The fix, verified live against the
//! exact syntax PipeWire ships in
//! `/usr/share/pipewire/filter-chain/sink-mix-FL-FR.conf`: a builtin
//! `mixer` node with `control = { "Gain 1" = 0.5, "Gain 2" = 0.5 }`, wired
//! via graph-level `inputs`/`outputs` arrays (these arrays' *length* sets
//! the mixer's port count — not a `config` key, and not the `control` map
//! alone, which was the source of an earlier failed attempt in this
//! session that defaulted to 8 fixed input ports).
//!
//! Verified with generated tone fixtures through the real
//! `filter-chain.service` + conf.d mechanism: L-only and R-only each
//! measure exactly half the RMS of L+R together, and a 0.92 FS stereo
//! input produces zero clipped samples (vs. 63.2% with the naive default).
//! See `engine/tests/downmix.rs` for the live acceptance test.

use std::io::Write;

/// The permanent source's fixed, device-independent node name. Chosen once
/// here; per R1, this must never be derived from any physical device.
pub const SOURCE_NAME: &str = "antibising_mic";

/// Fragment content, computed from typed config and rendered as
/// PipeWire's SPA-JSON-like config language (hand-built text, not a
/// generic serializer output — the format is not JSON: bare keys, no
/// commas between object members).
pub struct FragmentConfig {
    /// Whether RNNoise is in the graph. `false` is U2's bypass-only graph
    /// (downmix + copy); `true` adds the RNNoise node between them (U5).
    pub denoise_enabled: bool,
    /// RNNoise VAD Threshold (%), only meaningful when `denoise_enabled`.
    pub vad_threshold: f64,
}

impl Default for FragmentConfig {
    fn default() -> Self {
        Self {
            denoise_enabled: false,
            vad_threshold: 95.0,
        }
    }
}

/// Render the filter-chain fragment. The graph always downmixes 2ch->1ch
/// explicitly (the mixer node, gain 0.5/0.5) upstream of everything else;
/// U5 inserts the RNNoise node between the mixer and the playback side.
pub fn render(config: &FragmentConfig) -> String {
    let mixer_node = r#"                    {
                        name  = mix
                        type  = builtin
                        label = mixer
                        control = {
                          "Gain 1" = 0.5
                          "Gain 2" = 0.5
                        }
                    }"#;

    let (nodes, links, outputs) = if config.denoise_enabled {
        let rnnoise_node = format!(
            r#"                    {{
                        type   = ladspa
                        name   = rnnoise
                        plugin = "librnnoise_ladspa"
                        label  = noise_suppressor_mono
                        control = {{
                          "VAD Threshold (%)" = {vad:.1}
                        }}
                    }}"#,
            vad = config.vad_threshold
        );
        (
            format!("{mixer_node}\n{rnnoise_node}"),
            "                links = [\n                    { output = \"mix:Out\" input = \"rnnoise:In\" }\n                ]\n".to_string(),
            r#""rnnoise:Out""#,
        )
    } else {
        (mixer_node.to_string(), String::new(), r#""mix:Out""#)
    };

    format!(
        r#"# Generated by antibising — DO NOT EDIT.
# Regenerated from the daemon's config.toml on every change (KTD6).
# This file is inert until the next `filter-chain.service` start (Q8) —
# writing it never disrupts a running graph.
context.modules = [
    {{ name = libpipewire-module-filter-chain
        args = {{
            node.description = "antibising permanent microphone"
            media.name       = "antibising permanent microphone"
            filter.graph = {{
                nodes = [
{nodes}
                ]
{links}                inputs  = [ "mix:In 1" "mix:In 2" ]
                outputs = [ {outputs} ]
            }}
            capture.props = {{
                node.name         = "{source_name}_capture"
                audio.position    = [ FL FR ]
                node.passive      = true
                stream.dont-remix = true
            }}
            playback.props = {{
                node.name         = "{source_name}"
                media.class       = "Audio/Source"
                audio.position    = [ MONO ]
                stream.dont-remix = true
            }}
        }}
    }}
]
"#,
        nodes = nodes,
        links = links,
        outputs = outputs,
        source_name = SOURCE_NAME,
    )
}

/// Write the fragment atomically: temp file in the same directory, then
/// `rename()` over the target. `rename()` is atomic within one filesystem,
/// so a crash mid-write leaves either the old valid fragment or the new
/// complete one — never a truncated file `filter-chain.service` fails to
/// parse on its next start.
pub fn write_atomic(path: &std::path::Path, content: &str) -> std::io::Result<()> {
    let dir = path.parent().ok_or_else(|| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "fragment path has no parent",
        )
    })?;
    std::fs::create_dir_all(dir)?;

    let pid = std::process::id();
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let tmp_path = dir.join(format!(".antibising-fragment-{pid}-{nanos}.tmp"));

    {
        use std::os::unix::fs::OpenOptionsExt;
        let mut tmp = std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(&tmp_path)?;
        tmp.write_all(content.as_bytes())?;
        tmp.flush()?;
    } // tmp closed here, before rename

    std::fs::rename(&tmp_path, path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bypass_render_is_deterministic() {
        let cfg = FragmentConfig::default();
        let a = render(&cfg);
        let b = render(&cfg);
        assert_eq!(a, b, "same config must render byte-identical output");
    }

    #[test]
    fn bypass_graph_has_no_rnnoise_node() {
        let cfg = FragmentConfig {
            denoise_enabled: false,
            ..Default::default()
        };
        let out = render(&cfg);
        assert!(!out.contains("rnnoise"));
        assert!(out.contains(r#"label = mixer"#));
        assert!(out.contains(r#""Gain 1" = 0.5"#));
        assert!(out.contains(r#""Gain 2" = 0.5"#));
    }

    #[test]
    fn denoise_graph_includes_rnnoise_with_threshold() {
        let cfg = FragmentConfig {
            denoise_enabled: true,
            vad_threshold: 72.5,
        };
        let out = render(&cfg);
        assert!(out.contains("rnnoise"));
        assert!(out.contains("noise_suppressor_mono"));
        assert!(out.contains("72.5"));
    }

    #[test]
    fn source_name_is_fixed_and_device_independent() {
        let out = render(&FragmentConfig::default());
        assert!(out.contains(SOURCE_NAME));
        assert!(!out.to_lowercase().contains("razer"));
        assert!(!out.to_lowercase().contains("bluez"));
    }

    #[test]
    fn write_atomic_round_trips() {
        let dir = std::env::temp_dir().join(format!("antibising-fragtest-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("test.conf");
        let content = render(&FragmentConfig::default());
        write_atomic(&path, &content).unwrap();
        let read_back = std::fs::read_to_string(&path).unwrap();
        assert_eq!(read_back, content);
        std::fs::remove_dir_all(&dir).ok();
    }
}
