//! Bootstrap install/uninstall (U3) and minimal startup reconciliation
//! (Q4). Per the plan's KTD7/U3 split: **installation is a one-shot,
//! user-initiated act** (`antibisingd install`), never something the
//! service performs on its own — the service, when systemd starts it,
//! only ever wakes into an already-installed world and runs the Q4
//! reconciliation in this module to adopt/repair/start.
//!
//! Three files make up the install, per the Product Contract's
//! Dependencies section:
//! 1. `~/.config/systemd/user/antibisingd.service` — the daemon's own
//!    unit (`Wants=`/`After=pipewire.service`, never `BindsTo` — the
//!    daemon must outlive a PipeWire crash to run U1's reconnect).
//! 2. `~/.config/pipewire/filter-chain.conf.d/<fragment>.conf` — the
//!    permanent source (delegates rendering to [`crate::fragment`]).
//! 3. `~/.config/systemd/user/pipewire.service.d/<dropin>.conf` — the
//!    `Upholds=filter-chain.service` drop-in that makes R2's crash
//!    recovery real (measured: `BindsTo` on the shipped unit means a
//!    `SIGKILL` of PipeWire issues a *clean* stop, so `Restart=on-failure`
//!    never fires and nothing re-pulls an already-active target).
//!
//! All paths are parameterized through [`InstallPaths`] so unit tests can
//! point the whole bootstrap at a scratch directory without touching the
//! user's real systemd/PipeWire configuration; [`InstallPaths::production`]
//! is what `antibisingd install`/`uninstall` actually use.

use crate::fragment::{self, FragmentConfig};
use std::io;
use std::path::{Path, PathBuf};
use std::process::Command;

/// The daemon's own systemd user unit name.
pub const DAEMON_UNIT_NAME: &str = "antibisingd.service";
/// This product's fragment file in `filter-chain.conf.d/`. Numbered low so
/// it loads early relative to any fragments a user adds later.
pub const FRAGMENT_FILE_NAME: &str = "10-antibising-mic.conf";
/// The `pipewire.service.d` drop-in supplying `Upholds=` (R2).
pub const PIPEWIRE_DROPIN_NAME: &str = "10-antibising.conf";
/// The always-present, PipeWire-shipped unit that hosts the permanent
/// source (KTD4) — never templated per-install; this is fixed infra.
const FILTER_CHAIN_UNIT: &str = "filter-chain.service";

/// Every path the bootstrap reads or writes, parameterized so tests can
/// redirect the whole install into a scratch directory. `daemon_exec_path`
/// is the binary `ExecStart=` should invoke — normally the currently
/// running executable's own path.
pub struct InstallPaths {
    pub daemon_unit_path: PathBuf,
    pub fragment_path: PathBuf,
    pub pipewire_dropin_path: PathBuf,
    pub daemon_exec_path: PathBuf,
}

impl InstallPaths {
    /// Real install locations under `$XDG_CONFIG_HOME` (or `~/.config`),
    /// with the exec path resolved from the running binary.
    pub fn production() -> io::Result<Self> {
        let exec_path = std::env::current_exe()?;
        Ok(Self::at(config_home(), exec_path))
    }

    /// Build paths rooted at an arbitrary config directory — the entry
    /// point unit/integration tests use to avoid touching `~/.config`.
    pub fn at(config_dir: PathBuf, daemon_exec_path: PathBuf) -> Self {
        Self {
            daemon_unit_path: config_dir.join("systemd/user").join(DAEMON_UNIT_NAME),
            fragment_path: config_dir
                .join("pipewire/filter-chain.conf.d")
                .join(FRAGMENT_FILE_NAME),
            pipewire_dropin_path: config_dir
                .join("systemd/user/pipewire.service.d")
                .join(PIPEWIRE_DROPIN_NAME),
            daemon_exec_path,
        }
    }
}

fn config_home() -> PathBuf {
    std::env::var("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            PathBuf::from(std::env::var("HOME").expect("HOME must be set")).join(".config")
        })
}

/// Render `antibisingd.service`. `Wants=`/`After=pipewire.service` orders
/// startup without gating on it (`After=` is not a readiness guarantee —
/// U1's initial connect retries independently); deliberately not
/// `BindsTo=`, since the daemon must survive a PipeWire crash to run its
/// own reconnect (U1) rather than dying with it.
pub fn render_daemon_unit(exec_path: &Path) -> String {
    format!(
        r#"# Generated by `antibisingd install` — DO NOT EDIT.
[Unit]
Description=antibising permanent-microphone daemon
Wants=pipewire.service
After=pipewire.service

[Service]
Type=simple
ExecStart={exec} run
Restart=on-failure

[Install]
WantedBy=default.target
"#,
        exec = exec_path.display(),
    )
}

/// Render the `pipewire.service.d` drop-in. `Upholds=` (systemd >= 249)
/// continuously re-pulls `filter-chain.service` instead of waiting for a
/// target activation — verified across two consecutive `SIGKILL`s of
/// `pipewire.service` this session.
pub fn render_pipewire_dropin() -> String {
    r#"# Generated by `antibisingd install` — DO NOT EDIT.
# Keeps filter-chain.service running across a PipeWire crash (R2):
# BindsTo=pipewire.service (the shipped unit's own directive) issues a
# *clean* stop when PipeWire dies, so Restart=on-failure never fires and
# an already-active default.target never re-pulls the unit. Upholds=
# fixes this by continuously re-pulling the unit instead.
[Unit]
Upholds=filter-chain.service
"#
    .to_string()
}

fn run_systemctl(args: &[&str]) -> io::Result<()> {
    let mut full_args = vec!["--user"];
    full_args.extend_from_slice(args);
    let status = Command::new("systemctl").args(&full_args).status()?;
    if status.success() {
        Ok(())
    } else {
        Err(io::Error::other(format!(
            "systemctl --user {} failed: {status}",
            args.join(" ")
        )))
    }
}

/// `systemctl --user is-active <unit>` — true only on a clean `active`
/// exit; any other status (inactive, failed, unknown unit) is `false`.
pub fn is_unit_active(unit: &str) -> bool {
    Command::new("systemctl")
        .args(["--user", "is-active", "--quiet", unit])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// `systemctl --user is-enabled <unit>` — true only on a clean `enabled`
/// exit; disabled, static, or unknown units are `false`.
fn is_unit_enabled(unit: &str) -> bool {
    Command::new("systemctl")
        .args(["--user", "is-enabled", "--quiet", unit])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

fn write_file(path: &Path, content: &str) -> io::Result<()> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)?;
    }
    std::fs::write(path, content)
}

/// Idempotent bootstrap: write all three files, then wire them up
/// (`daemon-reload`, enable + start both units). Running this twice
/// produces no duplicate files and no second source — every write
/// replaces its target outright rather than appending.
///
/// **Rolls back only what this invocation itself changed.** If any step
/// fails partway through, restoring via a blind [`uninstall`] would be
/// destructive on a re-install: an already-working install (files
/// present, units enabled+active from a *previous* successful run)
/// would be disabled and its files deleted just because *this* attempt
/// failed later — e.g. re-running `install` as a repair step whose
/// final `enable --now` transiently fails must not tear down the
/// existing working microphone. So the prior state (each file's
/// previous content, if any, and whether each unit was already enabled)
/// is snapshotted before any writes happen; on failure, only file
/// contents are restored (or the file removed, if it didn't exist
/// before) and only units that were *not already enabled* are
/// disabled+stopped — a unit that was already enabled and active before
/// this call is left exactly as it was.
pub fn install(paths: &InstallPaths) -> io::Result<()> {
    let prior = snapshot_prior_state(paths);
    match install_inner(paths) {
        Ok(()) => Ok(()),
        Err(e) => {
            restore_prior_state(paths, &prior);
            Err(e)
        }
    }
}

/// What existed before this `install` call touched anything — captured
/// so a failure partway through can restore exactly that, and nothing
/// more.
struct PriorState {
    daemon_unit: PriorFile,
    fragment: PriorFile,
    pipewire_dropin: PriorFile,
    daemon_unit_was_enabled: bool,
    filter_chain_was_enabled: bool,
}

/// A file's state before this invocation touched it. Distinguishes
/// "didn't exist" from "existed but couldn't be read" — conflating the
/// two via `Result::ok()` would make `restore_file` **delete** a real
/// pre-existing file on a transient read error (permission glitch,
/// I/O hiccup) instead of leaving it alone, which is strictly worse
/// than a no-op restore of that one file.
#[derive(Debug)]
enum PriorFile {
    Absent,
    Present(String),
    /// Existed, but reading it failed for a reason other than "not
    /// found" — restore must not guess and must not delete.
    Unreadable,
}

fn snapshot_file(path: &Path) -> PriorFile {
    match std::fs::read_to_string(path) {
        Ok(content) => PriorFile::Present(content),
        Err(e) if e.kind() == io::ErrorKind::NotFound => PriorFile::Absent,
        Err(_) => PriorFile::Unreadable,
    }
}

fn snapshot_prior_state(paths: &InstallPaths) -> PriorState {
    PriorState {
        daemon_unit: snapshot_file(&paths.daemon_unit_path),
        fragment: snapshot_file(&paths.fragment_path),
        pipewire_dropin: snapshot_file(&paths.pipewire_dropin_path),
        daemon_unit_was_enabled: is_unit_enabled(DAEMON_UNIT_NAME),
        filter_chain_was_enabled: is_unit_enabled(FILTER_CHAIN_UNIT),
    }
}

fn restore_prior_state(paths: &InstallPaths, prior: &PriorState) {
    // Same Upholds= race as `uninstall` (see its doc comment): the
    // pipewire.service.d drop-in must be restored/removed and
    // daemon-reload run *before* attempting to disable
    // filter-chain.service, or a still-effective Upholds= re-pulls the
    // unit out from under `disable --now`.
    restore_file(&paths.pipewire_dropin_path, &prior.pipewire_dropin);
    let _ = run_systemctl(&["daemon-reload"]);

    restore_file(&paths.daemon_unit_path, &prior.daemon_unit);
    restore_file(&paths.fragment_path, &prior.fragment);

    // Only disable a unit this invocation itself may have enabled — a
    // unit that was already enabled (a pre-existing working install)
    // must never be touched by a rollback of a *later* failed call.
    if !prior.daemon_unit_was_enabled {
        let _ = run_systemctl(&["disable", "--now", DAEMON_UNIT_NAME]);
    }
    if !prior.filter_chain_was_enabled {
        let _ = run_systemctl(&["disable", "--now", FILTER_CHAIN_UNIT]);
    }
    let _ = run_systemctl(&["daemon-reload"]);
}

fn restore_file(path: &Path, prior: &PriorFile) {
    match prior {
        PriorFile::Present(content) => {
            let _ = write_file(path, content);
        }
        PriorFile::Absent => {
            let _ = std::fs::remove_file(path);
        }
        PriorFile::Unreadable => {
            // Unknown prior content -- leave whatever this invocation
            // wrote in place rather than guessing. Not silent: surfaced
            // via tracing in the daemon binary's own error path (the
            // engine crate has no logging dependency of its own).
        }
    }
}

fn install_inner(paths: &InstallPaths) -> io::Result<()> {
    write_file(
        &paths.daemon_unit_path,
        &render_daemon_unit(&paths.daemon_exec_path),
    )?;
    fragment::write_atomic(
        &paths.fragment_path,
        &fragment::render(&FragmentConfig::default()),
    )?;
    write_file(&paths.pipewire_dropin_path, &render_pipewire_dropin())?;

    run_systemctl(&["daemon-reload"])?;
    run_systemctl(&["enable", "--now", FILTER_CHAIN_UNIT])?;
    run_systemctl(&["enable", "--now", DAEMON_UNIT_NAME])?;
    Ok(())
}

/// Reverse of [`install`]: stop + disable both units, remove all three
/// files. Best-effort on the stop/disable calls — an already-stopped or
/// already-removed unit must not fail uninstall (idempotent in the same
/// sense as `install`).
///
/// **Order matters:** the `pipewire.service.d` drop-in (`Upholds=
/// filter-chain.service`) is removed and `daemon-reload`d **before**
/// attempting to stop `filter-chain.service`. `Upholds=` continuously
/// re-pulls its target for as long as `pipewire.service` stays active
/// (systemd's own semantics — it's not just a start-once `Wants=`) —
/// which is exactly R2's point, but it also means a `disable --now`
/// issued *while the drop-in is still in effect* loses the race:
/// systemd restarts the unit again before `disable --now` returns,
/// leaving `filter-chain.service` active after `uninstall` claims to
/// have stopped it. Removing the drop-in first breaks the Upholds=
/// relationship, so the subsequent stop actually sticks.
pub fn uninstall(paths: &InstallPaths) -> io::Result<()> {
    match std::fs::remove_file(&paths.pipewire_dropin_path) {
        Ok(()) => {}
        Err(e) if e.kind() == io::ErrorKind::NotFound => {}
        Err(e) => return Err(e),
    }
    run_systemctl(&["daemon-reload"])?;

    let _ = run_systemctl(&["disable", "--now", DAEMON_UNIT_NAME]);
    let _ = run_systemctl(&["disable", "--now", FILTER_CHAIN_UNIT]);

    for path in [&paths.daemon_unit_path, &paths.fragment_path] {
        match std::fs::remove_file(path) {
            Ok(()) => {}
            Err(e) if e.kind() == io::ErrorKind::NotFound => {}
            Err(e) => return Err(e),
        }
    }
    run_systemctl(&["daemon-reload"])?;
    Ok(())
}

/// Startup reconciliation (Q4): what the daemon should do about
/// `filter-chain.service` given two observed facts — whether the unit
/// reports `active`, and whether the permanent source node is actually
/// present on the graph right now. Four combinations, each mapping to
/// exactly one action, so a daemon start never creates a duplicate
/// source and never blindly restarts a source that's already correct.
/// U9 folds this into the daemon's fuller lifecycle handling; here it
/// covers only what U3's own install/uninstall unit needs.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StartupAction {
    /// Steady state, or the unit is inactive but the source is somehow
    /// already present (graph truth wins over systemd's view — per
    /// KTD5's philosophy, an observed node is stronger evidence than a
    /// unit-state query that may simply be stale).
    Adopt,
    /// Unit inactive, no source: the ordinary cold-start case. The
    /// fragment is already installed; starting the unit is sufficient.
    StartFilterChain,
    /// Unit reports active but the source doesn't appear — the fragment
    /// is missing, corrupt, or was hand-edited into something else (R7).
    /// Regenerate it from config and restart the unit once.
    RegenerateAndRestart,
}

pub fn classify_startup(unit_active: bool, source_present: bool) -> StartupAction {
    match (unit_active, source_present) {
        (_, true) => StartupAction::Adopt,
        (false, false) => StartupAction::StartFilterChain,
        (true, false) => StartupAction::RegenerateAndRestart,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classify_steady_state_adopts() {
        assert_eq!(classify_startup(true, true), StartupAction::Adopt);
    }

    #[test]
    fn classify_unit_inactive_source_present_adopts() {
        // Graph truth wins: the source existing matters more than
        // systemd's (possibly stale) view of the unit.
        assert_eq!(classify_startup(false, true), StartupAction::Adopt);
    }

    #[test]
    fn classify_cold_start_starts_filter_chain() {
        assert_eq!(
            classify_startup(false, false),
            StartupAction::StartFilterChain
        );
    }

    #[test]
    fn classify_active_but_source_missing_regenerates_and_restarts() {
        assert_eq!(
            classify_startup(true, false),
            StartupAction::RegenerateAndRestart
        );
    }

    #[test]
    fn install_paths_are_scoped_to_config_dir() {
        let paths = InstallPaths::at(
            PathBuf::from("/tmp/antibising-scratch"),
            PathBuf::from("/usr/bin/antibisingd"),
        );
        assert_eq!(
            paths.daemon_unit_path,
            PathBuf::from("/tmp/antibising-scratch/systemd/user/antibisingd.service")
        );
        assert_eq!(
            paths.fragment_path,
            PathBuf::from(
                "/tmp/antibising-scratch/pipewire/filter-chain.conf.d/10-antibising-mic.conf"
            )
        );
        assert_eq!(
            paths.pipewire_dropin_path,
            PathBuf::from(
                "/tmp/antibising-scratch/systemd/user/pipewire.service.d/10-antibising.conf"
            )
        );
    }

    #[test]
    fn daemon_unit_never_uses_binds_to() {
        // R2's whole point: BindsTo would die *with* PipeWire instead of
        // surviving to run U1's reconnect.
        let out = render_daemon_unit(Path::new("/usr/bin/antibisingd"));
        assert!(!out.contains("BindsTo"));
        assert!(out.contains("Wants=pipewire.service"));
        assert!(out.contains("After=pipewire.service"));
        assert!(out.contains("Restart=on-failure"));
        assert!(out.contains("/usr/bin/antibisingd run"));
    }

    #[test]
    fn pipewire_dropin_declares_upholds() {
        let out = render_pipewire_dropin();
        assert!(out.contains("Upholds=filter-chain.service"));
    }

    #[test]
    fn install_write_is_idempotent_on_files() {
        let dir = std::env::temp_dir().join(format!(
            "antibising-install-unittest-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let paths = InstallPaths::at(dir.clone(), PathBuf::from("/usr/bin/antibisingd"));

        // Write directly (bypassing systemctl, which unit tests must not
        // invoke) to prove the file-writing half is idempotent and
        // produces no duplicates.
        write_file(
            &paths.daemon_unit_path,
            &render_daemon_unit(&paths.daemon_exec_path),
        )
        .unwrap();
        write_file(
            &paths.daemon_unit_path,
            &render_daemon_unit(&paths.daemon_exec_path),
        )
        .unwrap();
        let content = std::fs::read_to_string(&paths.daemon_unit_path).unwrap();
        assert!(content.contains("antibisingd run"));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn restore_file_writes_back_prior_content_or_removes_new_file() {
        // Covers the file-restoration half of rollback (the systemctl
        // half can't be exercised in a unit test): a file that existed
        // before this invocation is restored to its exact prior content;
        // a file that did NOT exist before (this invocation created it)
        // is removed entirely rather than left behind.
        let dir = std::env::temp_dir().join(format!(
            "antibising-restore-unittest-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();

        // Case 1: a pre-existing file must come back exactly as it was.
        let existing = dir.join("existing.conf");
        std::fs::write(&existing, "original content").unwrap();
        std::fs::write(&existing, "new content that would be written by install").unwrap();
        restore_file(&existing, &PriorFile::Present("original content".to_string()));
        assert_eq!(std::fs::read_to_string(&existing).unwrap(), "original content");

        // Case 2: a file that didn't exist before must be removed, not
        // left as whatever this invocation wrote.
        let newly_created = dir.join("newly-created.conf");
        std::fs::write(&newly_created, "written by this failed install attempt").unwrap();
        restore_file(&newly_created, &PriorFile::Absent);
        assert!(!newly_created.exists());

        // Case 3: a file that existed but couldn't be read (permission
        // glitch, transient I/O error) must be left exactly as this
        // invocation wrote it -- restore must not guess at content it
        // never actually observed, and must not delete a file that DID
        // exist before just because reading it failed.
        let unreadable_prior = dir.join("unreadable-prior.conf");
        std::fs::write(&unreadable_prior, "written by this failed install attempt").unwrap();
        restore_file(&unreadable_prior, &PriorFile::Unreadable);
        assert_eq!(
            std::fs::read_to_string(&unreadable_prior).unwrap(),
            "written by this failed install attempt",
            "Unreadable prior must leave the newly-written content untouched"
        );

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn snapshot_file_distinguishes_absent_from_present() {
        let dir = std::env::temp_dir().join(format!(
            "antibising-snapshot-unittest-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();

        let missing = dir.join("does-not-exist.conf");
        assert!(matches!(snapshot_file(&missing), PriorFile::Absent));

        let present = dir.join("exists.conf");
        std::fs::write(&present, "hello").unwrap();
        match snapshot_file(&present) {
            PriorFile::Present(content) => assert_eq!(content, "hello"),
            other => panic!("expected Present, got a different variant: {other:?}"),
        }

        std::fs::remove_dir_all(&dir).ok();
    }
}
